### ISSUE TITLE
KeyError in Dependency Injection with Pydantic and aioinject Using Union Types

### ISSUE THREAD

**Issue by leo-gall** [ThirVondukr/aioinject#19]
Hello,
I wanted to inject a `BaseSettings` class from [Pydantic Settings](https://docs.pydantic.dev/latest/concepts/pydantic_settings) today, but unfortunately an error is thrown (`KeyError: bool | None`). I suspect that the problem is not related to this library, but rather to the union type in general (correct me if I'm wrong). Below you can find the error and my code. I'm using Python v3.12.7, aioinject v0.35.3 and Pydantic Settings v2.7.0

```py

import aioinject
from aioinject import Container

container = Container()

class SecurityConfig(BaseSettings):
    hallo: str = "hey"

def register_dependencies():
    container.register(
        aioinject.Singleton(SecurityConfig),
    )

def create_app() -> FastAPI:
    dotenv.load_dotenv()
    app = FastAPI()

    register_dependencies()

    with container.sync_context() as ctx:
        security_config = ctx.resolve(SecurityConfig)

       # Code where I want to use the config...

        return app


app = create_app()
````

```
AttributeError: 'types.UnionType' object has no attribute '__qualname__'
WARNING:  WatchFiles detected changes in 'daytistics/config.py'. Reloading...
Process SpawnProcess-14:
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/aioinject/containers.py", line 55, in get_provider
    return self.providers[type_]
           ~~~~~~~~~~~~~~^^^^^^^
KeyError: bool | None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 80, in subprocess_started
    target(sockets=sockets)
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/app/daytistics/main.py", line 40, in <module>
    app = create_app()
          ^^^^^^^^^^^^
  File "/app/daytistics/main.py", line 26, in create_app
    security_config = ctx.resolve(SecurityConfig)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/aioinject/context.py", line 187, in resolve
    dependencies[dependency.name] = self.resolve(
                                    ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/aioinject/context.py", line 178, in resolve
    provider = self._get_provider(type_)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/aioinject/context.py", line 64, in _get_provider
    return self._providers.get(type_) or self._container.get_provider(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/aioinject/containers.py", line 57, in get_provider
    err_msg = f"Provider for type {type_.__qualname__} not found"
```

**Comment by ThirVondukr** [comment]
@leo-gall Docs mention it: https://thirvondukr.github.io/aioinject/cookbook/
The problem is that `pydantic-settings` classes already have an init which doesn't have the same parameters as the fields you defined (unlike `dataclasses` for example) and `aioinject` tries to provide one of the parameters.
You can either use the code snippet from documentation and create all settings instances on container initialization, but if you want to make them "lazy" and only initialize them when they're required you could use `functools.partial`:
```py
_settings_classes: Sequence[type[BaseSettings]] = [
    AppSettings,
    DatabaseSettings,
]

for settings_cls in _settings_classes:
    container.register(Singleton(functools.partial(settings_cls), type_=settings_cls))
